# Yarn Configuration
# Ensures consistent behavior across all environments

# Use node-modules linker instead of PnP for better compatibility
nodeLinker: node-modules

# Enable scripts
enableScripts: true

# Use npm registry
npmRegistryServer: "https://registry.npmjs.org"

# Improve performance
compressionLevel: mixed
enableGlobalCache: true

# Install state
installStatePath: ".yarn/install-state.gz"
