const REFRESH_TOKEN_EXPIRES_DAYS = 7;
export const MAX_ACTIVE_HABITS = 5;
export const WARN_ACTIVE_HABITS = 3;
export const BCRYPT_ROUNDS = 12;
export const ACCESS_TOKEN_EXPIRES = "15m";
export const REFRESH_TOKEN_EXPIRES = `${REFRESH_TOKEN_EXPIRES_DAYS}d` as const;
export const REFRESH_TOKEN_EXPIRES_MS = REFRESH_TOKEN_EXPIRES_DAYS * 24 * 60 * 60 * 1000;
